- name: Installing Packages on Container
  hosts: docker
  gather_facts: no
  tasks:
  - name: installing yum package
    package:
      name: "httpd"
      state: present
    register: install

  - name: installing httpd package
    debug:
      var: install

  - name: starting service
    command: "/usr/sbin/httpd"
    register: srvc

  - name: output of srvc command
    debug:
      var: srvc.stderr_lines

  - name: creating html file
    copy:
      content: "Hello, this is Task 14.2"
      dest: "/var/www/html/index.html"
