---
-  name: Configuring Master
   hosts: tag_Name_Master
   ignore_errors: yes
   become: yes
   vars_files:
       - vars.yml
   roles:
       - master


-  name: Configuring Slaves
   hosts: tag_Name_Slaves
   ignore_errors: yes
   become: yes
   vars_files:
       - vars.yml
   roles:
       - slave
   post_tasks:
       -  name: "Copying Shell Script File to Slaves"
          template:
           src: token.j2
           dest: "/root/token.sh"
           owner: root
           group: root
           mode: '777'
           force: yes

       -  name: "Running Script"
          command: "./token.sh"
          args:
           chdir: /root/

